apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::126419258799:role/my-bank-eks-node-role
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::126419258799:user/github-ci
      username: github-ci
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-06T12:20:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "15721"
  uid: 05bb218e-6b6a-4725-b2d7-17f9dd7dd759
